name: examples

on:
  push:
    branches:
      - "main"
      - "v0-3-x"
  pull_request:
    branches:
      - "main"
      - "v0-3-x"
  schedule:
    - cron: "0 0 * * *"

defaults:
  run:
    shell: bash -l {0}

jobs:

  test:

    name: 💻 ${{ matrix.os }}, 🐍 ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}

    env:
      OE_LICENSE: ${{ github.workspace }}/oe_license.txt

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
        python-version:
          - 3.8
          - 3.9

    steps:
      - uses: actions/checkout@v3.0.2

      - name: Setup Conda Environment
        uses: conda-incubator/setup-miniconda@v2.1.1
        with:

          python-version: ${{ matrix.python-version }}
          environment-file: devtools/conda-envs/test_env.yaml

          activate-environment: test

          auto-update-conda: true
          auto-activate-base: false

          show-channel-urls: true

      - name: Install PASCAL Compiler (MacOS)
        if: startsWith(matrix.os, 'macOS')
        run: |
          brew install fpc

      - name: Install PASCAL Compiler (Ubuntu)
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo apt-get install fp-compiler

      - name: Install checkmol
        run: |

          curl https://homepage.univie.ac.at/norbert.haider/download/chemistry/checkmol/checkmol.pas > checkmol.pas
          fpc checkmol.pas -S2

          echo $(pwd) >> $GITHUB_PATH

      - name: Install Package
        run: |

          python setup.py develop --no-deps

      - name: Conda Environment Information
        run: |
          conda info
          conda list

      - name: Run examples
        run: |

          pytest -v --cov=openff --cov-report=xml --nbval-lax docs/tutorials/

      - name: Code coverage
        uses: codecov/codecov-action@v3.1.0
        with:
          file: ./coverage.xml
          flags: unittests
          name: codecov-${{ matrix.os }}-py${{ matrix.python-version }}
